-- MySQL Script generated by MySQL Workbench
-- 01/21/16 21:42:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema turbo-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema turbo-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `turbo-db` DEFAULT CHARACTER SET utf8 ;
USE `turbo-db` ;

-- -----------------------------------------------------
-- Table `turbo-db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turbo-db`.`users` (
  `user_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(254) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `user_id_idx` (`user_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COMMENT = 'This is the users table';


-- -----------------------------------------------------
-- Table `turbo-db`.`records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turbo-db`.`records` (
  `record_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `data` LONGTEXT NOT NULL,
  `publish_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL DEFAULT NULL,
  `deleted` ENUM('true', 'false') NULL DEFAULT 'false',
  `user_editor` VARCHAR(45) NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC),
  INDEX `user_jd_idx` (`user_id` ASC),
  CONSTRAINT `user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `turbo-db`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COMMENT = 'This is where the data is.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
