-- MySQL Script generated by MySQL Workbench
-- 05/12/16 01:36:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema twitter_clone
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema twitter_clone
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `twitter_clone` DEFAULT CHARACTER SET utf8 ;
USE `twitter_clone` ;

-- -----------------------------------------------------
-- Table `twitter_clone`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twitter_clone`.`users` (
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `birth_date` TIMESTAMP NULL DEFAULT NULL,
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `profile_img_id` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `twitter_clone`.`credentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twitter_clone`.`credentials` (
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `users_id_user` INT(11) NOT NULL,
  `credential_id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`credential_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `credential_id_UNIQUE` (`credential_id` ASC),
  UNIQUE INDEX `users_id_user_UNIQUE` (`users_id_user` ASC),
  INDEX `fk_credentials_users1_idx` (`users_id_user` ASC),
  CONSTRAINT `fk_credentials_users`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `twitter_clone`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `twitter_clone`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twitter_clone`.`likes` (
  `like_id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`like_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `twitter_clone`.`tweets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twitter_clone`.`tweets` (
  `tweet_id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(172) NOT NULL,
  `created_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP())
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_clone`.`tweets_has_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twitter_clone`.`tweets_has_likes` (
  `tweets_tweet_id` INT(11) NOT NULL,
  `tweets_users_id_user` INT(11) NOT NULL,
  `likes_like_id` INT(11) NOT NULL,
  PRIMARY KEY (`tweets_tweet_id`, `tweets_users_id_user`, `likes_like_id`),
  INDEX `fk_tweets_has_likes_likes1_idx` (`likes_like_id` ASC),
  CONSTRAINT `fk_tweets_has_likes_likes1`
    FOREIGN KEY (`likes_like_id`)
    REFERENCES `twitter_clone`.`likes` (`like_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `twitter_clone`.`users_has_followers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twitter_clone`.`users_has_followers` (
  `user_id` INT(11) NOT NULL,
  `follower_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`, `follower_user_id`),
  INDEX `fk_users_has_users_users1_idx` (`follower_user_id` ASC),
  INDEX `fk_users_has_users_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_has_users_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `twitter_clone`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_users_users1`
    FOREIGN KEY (`follower_user_id`)
    REFERENCES `twitter_clone`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
